# syntax=docker/dockerfile:1
FROM ghcr.io/chroma-core/chroma:latest
RUN apt-get update -y && apt-get install -o Acquire::ForceIPv4=true -y curl

CMD ["uvicorn", "chromadb.app:app", "--workers", "1", "--host", "0.0.0.0", "--port", "8000", "--log-config", "log_config.yml"]
