# syntax=docker/dockerfile:1
FROM docker.io/pytorch/pytorch:2.2.0-cuda12.1-cudnn8-devel
RUN mkdir -p /root/A2rchi
WORKDIR /root/A2rchi

# maybe just throw everything into the same requirements file in the first place....
COPY requirements.txt requirements.txt
COPY LICENSE LICENSE

RUN pip install --upgrade pip && pip install -r requirements.txt

RUN apt-get update && apt-get install -y \
    nvidia-utils-550 \
    libnvidia-compute-550 \
    && rm -rf /var/lib/apt/lists/*

# Install Firefox and Geckodriver for Selenium 
RUN apt-get update && apt-get install -y \
    wget \
    libnss3 \
    libgconf-2-4 \
    libx11-xcb1 \
    libxcomposite1 \
    libxcursor1 \
    libxdamage1 \
    libxext6 \
    libxi6 \
    libxtst6 \
    libxrandr2 \
    libasound2 \
    libdbus-glib-1-2 \
    && rm -rf /var/lib/apt/lists/*
# Install Firefox ESR
RUN wget -O /tmp/firefox-esr.tar.bz2 "https://download.mozilla.org/?product=firefox-esr-latest-ssl&os=linux64&lang=en-US" && \
    tar -xjf /tmp/firefox-esr.tar.bz2 -C /opt/ && \
    ln -s /opt/firefox/firefox /usr/bin/firefox && \
    rm /tmp/firefox-esr.tar.bz2

# Install Geckodriver
RUN wget -q "https://github.com/mozilla/geckodriver/releases/download/v0.36.0/geckodriver-v0.36.0-linux64.tar.gz" \
    && tar -xzf "geckodriver-v0.36.0-linux64.tar.gz" -C /usr/local/bin \
    && chmod +x /usr/local/bin/geckodriver \
    && rm "geckodriver-v0.36.0-linux64.tar.gz"

COPY a2rchi_code a2rchi
COPY pyproject.toml pyproject.toml
COPY weblists weblists
RUN pip install --upgrade pip && pip install .
CMD ["python", "-u", "a2rchi/bin/service_grader.py"]
# service_grader.py will just run the flask app as in service_chat.py ... don't even need the janky javascript templating function
