# syntax=docker/dockerfile:1
FROM python:3.10
RUN mkdir -p /root/A2rchi
WORKDIR /root/A2rchi

COPY requirements.txt requirements.txt
COPY LICENSE LICENSE

RUN pip install --upgrade pip && pip install -r requirements.txt

COPY config config
COPY a2rchi a2rchi

CMD ["python", "-u", "a2rchi/bin/service_piazza.py"]
