# syntax=docker/dockerfile:1
ARG TAG
FROM a2rchi-base:${TAG}
# FROM mdr223/a2rchi:base-${TAG}
#EXPOSE 7861

# ensure this directory is present for prod-801 deployment
# RUN if [ "$BUILD_ENV" = "prod-801" ] ; then mkdir /root/data/801-content ; fi

COPY a2rchi_code a2rchi
COPY pyproject.toml pyproject.toml
COPY weblists weblists
RUN pip install --upgrade pip && pip install .

CMD ["python", "-u", "a2rchi/bin/service_chat.py"]
