# syntax=docker/dockerfile:1
ARG TAG=from-env
FROM a2rchi-base:${TAG}

COPY a2rchi_code a2rchi
COPY pyproject.toml pyproject.toml
RUN pip install --upgrade pip && pip install .

CMD ["python", "-u", "a2rchi/bin/service_cleo.py"]
