apiVersion: v1
kind: Secret
metadata:
  name: {{ name }}-secrets
  labels:
    app: {{ name }}
    component: secrets
type: Opaque
data:
  {%- for secret_name, encoded_secret in encoded_secrets.items() %}
  {{ secret_name }}: {{ encoded_secret }}
  {%- endfor %}