apiVersion: v1
kind: Secret
metadata:
  name: {{ name }}-secrets
  labels:
    app: {{ name }}-chat
    app:  {{ name }}-config-seed
    app: {{ name }}-data-manager
type: Opaque
data:
  {%- for secret_name, encoded_secret in encoded_secrets.items() %}
  {{ secret_name }}: {{ encoded_secret }}
  {%- endfor %}