{
 "title": "A2rchi Usage",
 "description": "Charts tracking A2rchi's usage.",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Number of Messages and Distinct Conversations",
   "type": "timeseries",
   "description": "Number of queries handled by A2rchi per-hour.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "-- number of messages per 15min window\nWITH msg_timing_info AS (\n  SELECT $__timeGroup(server_received_msg_ts, '1h', 0) as t1, count(mid) as num_msgs\n  FROM timing\n  WHERE $__timeFrom() <= server_received_msg_ts AND server_received_msg_ts <= $__timeTo()\n  GROUP BY 1\n  ORDER BY $__timeGroup(server_received_msg_ts, '1h', 0)\n), convo_timing_info AS ( -- number of unique conversations per 15 min window\n  SELECT $__timeGroup(server_received_msg_ts, '1h', 0) as t2, count(distinct(conversation_id)) as num_convos\n  FROM timing JOIN conversations ON timing.mid = conversations.message_id\n  WHERE $__timeFrom() <= server_received_msg_ts AND server_received_msg_ts <= $__timeTo()\n  GROUP BY 1\n  ORDER BY $__timeGroup(server_received_msg_ts, '1h', 0)\n), intervals AS (\n  SELECT $__timeGroupAlias(t, '1h', 0) FROM generate_series($__timeFrom(), $__timeTo(), '1 hour'::interval) AS s(t)\n), msgs_join_convos AS (\n  SELECT * FROM msg_timing_info JOIN convo_timing_info ON t1 = t2\n)\nSELECT time, num_msgs, num_convos FROM intervals LEFT OUTER JOIN msgs_join_convos ON t1 = intervals.time;\n"
    }
   ]
  },
  {
   "title": "A2rchi Response Time Histogram",
   "type": "histogram",
   "description": "Distribution of `msg_duration` column, which measures the total time from when the server receives the message to when it returns a response to the user.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "WITH msg_to_config AS (\n  SELECT message_id, config_name\n  FROM conversations JOIN configs ON conversations.conf_id = configs.config_id\n)\nSELECT server_received_msg_ts as time, extract(seconds from msg_duration) as all_gpt4\nFROM timing JOIN msg_to_config on timing.mid = msg_to_config.message_id\nWHERE server_received_msg_ts >= $__timeFrom() AND server_received_msg_ts < $__timeTo() and config_name = 'all_gpt4_config'\nORDER BY time"
    },
    {
     "rawSql": "WITH msg_to_config AS (\n  SELECT message_id, config_name\n  FROM conversations JOIN configs ON conversations.conf_id = configs.config_id\n)\nSELECT server_received_msg_ts as time, extract(seconds from msg_duration) as all_gpt35\nFROM timing JOIN msg_to_config on timing.mid = msg_to_config.message_id\nWHERE server_received_msg_ts >= $__timeFrom() AND server_received_msg_ts < $__timeTo() and config_name = 'all_gpt35_config'\nORDER BY time"
    },
    {
     "rawSql": "WITH msg_to_config AS (\n  SELECT message_id, config_name\n  FROM conversations JOIN configs ON conversations.conf_id = configs.config_id\n)\nSELECT server_received_msg_ts as time, extract(seconds from msg_duration) as mgpt35_sgpt4\nFROM timing JOIN msg_to_config on timing.mid = msg_to_config.message_id\nWHERE server_received_msg_ts >= $__timeFrom() AND server_received_msg_ts < $__timeTo() and config_name = 'mgpt35_sgpt4_config'\nORDER BY time"
    }
   ]
  },
  {
   "title": "Feedback",
   "type": "barchart",
   "description": "Bar chart tracking the feedback totals.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "WITH msg_to_config AS (\n  SELECT message_id, config_name\n  FROM conversations JOIN configs ON conversations.conf_id = configs.config_id\n), filtered_feedback AS (\n  SELECT mid, config_name, feedback, max(feedback_ts)\n  FROM feedback JOIN msg_to_config ON feedback.mid = msg_to_config.message_id\n  GROUP BY mid, config_name, feedback\n)\nSELECT count(*), TRIM(TRAILING '_config' FROM feedback || '_' || config_name) as feedback, config_name FROM filtered_feedback GROUP BY config_name, feedback;\n"
    }
   ]
  },
  {
   "title": "Conversations Length Histogram",
   "type": "histogram",
   "description": "A histogram showing the distribution of the number of messages per conversation.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT count(message_id)\nFROM conversations\nGROUP BY conversation_id"
    }
   ]
  }
 ]
}