apiVersion: v1
data:
  init.sql: |
    {{ .Files.Get "src/cli/templates/init.sql" | nindent 4 }}
kind: ConfigMap
metadata:
  name:  {{ include "archi.fullname" . }}-postgres-init
  labels:
    app: {{ include "archi.fullname" . }}-postgres
  annotations:
    use-subpath: "true"