apiVersion: v1
kind: Service
metadata:
  name: {{ include "archi.fullname" . }}-postgres
  labels:
    app: {{ include "archi.fullname" . }}-postgres
spec:
  selector:
    app: {{ include "archi.fullname" . }}-postgres
  ports:
    - name: postgres
      protocol: TCP
      port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}