apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {{ name }}-chatbot
  name:  {{ name }}-chatbot-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    {{ "{{- toYaml .Values.chat.pvc.resources | nindent 12 }}" }}
