apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {{ name }}-chatbot
  name:  {{ name }}-chatbot-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
