apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {{ name }}-chatbot
{% if volume_name == "archi-models" %}
  name:  {{ name }}-models-pvc
{% else %}
  name:  {{ name }}-chatbot-pvc
{% endif %}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
{% if volume_name == "archi-models" %}
    {{ "{{- toYaml .Values.chat.modelsPvc.resources | nindent 12 }}" }}
{% else %}
    {{ "{{- toYaml .Values.chat.pvc.resources | nindent 12 }}" }}
{% endif %}
