#!/bin/bash
#SBATCH --job-name=archi-services
#SBATCH --output=archi-services.%j.out
#SBATCH --error=archi-services.%j.out
#SBATCH --time=12:00:00                    # mit_normal hard cap is 12h; chain sbatches for longer
#SBATCH --cpus-per-task=8
#SBATCH --mem=32G
#SBATCH --partition=mit_normal             # ORCD CPU partition; override with --partition= on submit
#SBATCH --nodes=1
# (no GPU — the Archi services don't need one; the vLLM job is a sibling)

# Brings up the Archi data layer (postgres + data-manager + rucio-mcp) inside
# the current Slurm allocation using deploy_apptainer.sh. Writes the chosen
# node + ports to $HOME/archi-services.env so other Slurm jobs can find them.
#
# Required env on submit:
#   ARCHI_BUNDLE  path to archi-deployment-bundle-<date>.tar.zst (or a directory
#                 that already has the extracted bundle)
#   ARCHI_AGE_KEY path to the age private key file
#
# Optional env on submit:
#   PG_PORT, DM_PORT, RUCIO_PORT   (override defaults)
#   ARCHI_PERSISTENT                override persistent-state dir (default $HOME/.archi-bundle-state)
#
# Usage on the login node:
#   sbatch --export=ALL,ARCHI_BUNDLE=$HOME/archi-deployment-bundle-20260521.tar.zst,ARCHI_AGE_KEY=$HOME/.archi-bundle-key.txt \
#          scripts/slurm/start_archi_services.sh
#
# When the job is running, it writes $HOME/archi-services.env with:
#   ARCHI_BUNDLE_HOSTNAME=<chosen node>
#   ARCHI_POSTGRES_URL=postgresql://archi@<node>:<port>/archi-db
#   ARCHI_DM_URL=http://<node>:<port>
#   ARCHI_RUCIO_MCP_URL=http://<node>:<port>/mcp
#   SLURM_JOB_ID=<jobid>
# Other Slurm jobs (e.g. the 260q benchmark driver) can `source` this file.

set -euo pipefail

log()  { printf '[start_archi] %s\n' "$*" >&2; }
die()  { log "ERROR: $*"; exit 1; }

# ORCD compute nodes don't have apptainer on the default PATH; the module
# system has it as `apptainer/1.4.2`. Load it here so deploy_apptainer.sh's
# `have apptainer` check passes.
if command -v module >/dev/null 2>&1; then
  module load apptainer/1.4.2 2>/dev/null || module load apptainer 2>/dev/null || true
fi

[ -n "${ARCHI_BUNDLE:-}" ]   || die "ARCHI_BUNDLE env var required (path to .tar.zst or extracted dir)"
[ -n "${ARCHI_AGE_KEY:-}" ]  || die "ARCHI_AGE_KEY env var required"
[ -e "$ARCHI_BUNDLE" ]       || die "ARCHI_BUNDLE=$ARCHI_BUNDLE not found"
[ -f "$ARCHI_AGE_KEY" ]      || die "ARCHI_AGE_KEY=$ARCHI_AGE_KEY not found"

# ORCD apptainer is non-suid → no portmap → container binds directly to
# host ports. The bundle images hardcode 5436 (postgres -p 5436), 7871
# (data-manager config), and 8000 (rucio-mcp). Honour those; if they're
# in use on the chosen node, deploy_apptainer.sh's preflight will bail and
# we re-submit hoping for a different node.
export PG_PORT=${PG_PORT:-5436}
export DM_PORT=${DM_PORT:-7871}
export RUCIO_PORT=${RUCIO_PORT:-8000}
export ARCHI_BIND_HOST=$(hostname)
# Persistent state on NFS $HOME (survives across sbatch jobs).
# Subsequent runs reuse pg-data, sif cache, and corpus → ~30s restart.
export ARCHI_PERSISTENT=${ARCHI_PERSISTENT:-$HOME/.archi-bundle-state}
mkdir -p "$ARCHI_PERSISTENT"

log "Host:        $(hostname)"
log "Job:         $SLURM_JOB_ID"
log "Ports:       pg=$PG_PORT dm=$DM_PORT rucio=$RUCIO_PORT"
log "Persistent:  $ARCHI_PERSISTENT"
log "Bundle src:  $ARCHI_BUNDLE"

###############################################################################
# 1. Stage the bundle into the persistent dir (extract once, reuse forever)
###############################################################################
BUNDLE_DIR=$ARCHI_PERSISTENT/bundle
if [ -f "$ARCHI_BUNDLE" ] && [[ "$ARCHI_BUNDLE" == *.tar.zst ]]; then
  if [ ! -f "$BUNDLE_DIR/.extracted" ]; then
    log "Extracting bundle → $BUNDLE_DIR (1.6 GB, ~30-60s on NFS)…"
    mkdir -p "$BUNDLE_DIR"
    tar --use-compress-program='zstd -d' -xf "$ARCHI_BUNDLE" -C "$BUNDLE_DIR" --strip-components=1
    touch "$BUNDLE_DIR/.extracted"
  else
    log "Reusing already-extracted bundle at $BUNDLE_DIR"
  fi
elif [ -d "$ARCHI_BUNDLE" ]; then
  # Caller provided a dir already; symlink it into place
  if [ ! -e "$BUNDLE_DIR" ]; then ln -s "$ARCHI_BUNDLE" "$BUNDLE_DIR"; fi
else
  die "ARCHI_BUNDLE must be a .tar.zst file or an already-extracted directory"
fi

log "Bundle dir: $BUNDLE_DIR"

###############################################################################
# 2. Bring up the stack via deploy_apptainer.sh
###############################################################################
cd "$BUNDLE_DIR"
log "Running deploy_apptainer.sh…"
./deploy_apptainer.sh

###############################################################################
# 3. Publish endpoints to $HOME/archi-services.env
###############################################################################
{
  echo "# Generated by start_archi_services.sh at $(date -Iseconds)"
  echo "SLURM_JOB_ID=$SLURM_JOB_ID"
  cat endpoints.env
} > "$HOME/archi-services.env"

log "Wrote $HOME/archi-services.env. Contents:"
cat "$HOME/archi-services.env"

###############################################################################
# 4. Hold the allocation until the job hits its walltime or someone cancels
###############################################################################
log "Stack up. Holding allocation. To tear down early:"
log "  scancel $SLURM_JOB_ID"
log "  ( the trap below tears down the apptainer instances cleanly )"

cleanup() {
  log "Caught signal; stopping apptainer instances (persistent state at $ARCHI_PERSISTENT is preserved)…"
  cd "$BUNDLE_DIR" && ./deploy_apptainer.sh --teardown || true
  rm -f "$HOME/archi-services.env"
  log "Done. To fully reset persistent state: $BUNDLE_DIR/deploy_apptainer.sh --reset"
}
trap cleanup EXIT TERM INT

# Sleep until the job is killed. `wait` would only work if we had a child PID
# to wait on; sleep infinity is fine for a Slurm hold.
sleep infinity
