apiVersion: v1
data:
  {%- for file_name, content in grafana_dict.items() %}
  {{ file_name }}: |
    {{ content | indent(4) }}
  {%- endfor %}
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  name: {{ archi_name }}-grafana-config
