apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ name }}-grafana
  labels:
    app: {{ name }}-grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ name }}-grafana
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ name }}-grafana
      annotations:
        rollout-timestamp: {{ "{{ now | quote }}" }}
    spec:
      automountServiceAccountToken: false
      containers:
        - name: {{ name }}-grafana
          envFrom:
            - secretRef:
                name: {{ name }}-secrets
          env:
            - name: PGDATABASE
              value: archi-db
            - name: PGHOST
              value: {{ name }}-postgres
            - name: PGPORT
              value: "{{ "{{ .Values.postgres.port }}" }}"
            - name: PGUSER
              value: archi
            - name: VERBOSITY
              value: "{{ "{{ .Values.verbosity }}" }}"
          image: {{ "{{ .Values.grafana.image }}" }}
          ports:
          - containerPort: {{ "{{ .Values.grafana.externalPort }}" }}
            protocol: TCP
          volumeMounts:
            - mountPath: /root/data
              name: {{ name }}-chatbot-pvc
            - mountPath: /root/archi/configs
              name: {{ name }}-chat-config
            - mountPath: /etc/grafana/grafana.ini
              name: {{ name }}-grafana-config
              subPath: grafana.ini
            - mountPath: /etc/grafana/provisioning/dashboards/dashboards.yaml
              name: {{ name }}-grafana-config
              subPath: dashboards.yaml
            - mountPath: /etc/grafana/provisioning/datasources/datasources.yaml
              name: {{ name }}-grafana-config
              subPath: datasources.yaml
            - mountPath: /var/lib/grafana/dashboards/archi-default-dashboard.json
              name: {{ name }}-grafana-config
              subPath: archi-default-dashboard.json
      restartPolicy: Always
      volumes:
        - name: {{ name }}-chatbot-pvc
          persistentVolumeClaim:
            claimName: {{ name }}-chatbot-pvc
        - configMap:
            name: {{ name }}-chat-config
          name: {{ name }}-chat-config
        - configMap:
            items:
              - key: grafana.ini
                path: grafana.ini
              - key: dashboards.yaml
                path: dashboards.yaml
              - key: datasources.yaml
                path: datasources.yaml
              - key: archi-default-dashboard.json
                path: archi-default-dashboard.json
            name: {{ name }}-grafana-config
          name: {{ name }}-grafana-config