apiVersion: v1
kind: Service
metadata:
  name: {{ name }}-grafana
  labels:
    app: {{ name }}-grafana
spec:
  selector:
    app: {{ name }}-grafana
  ports:
    - name: grafana-port
      port: {{ "{{ .Values.grafana.port }}" }}  
      targetPort: {{ "{{ .Values.grafana.externalPort }}" }}  
