# syntax=docker/dockerfile:1
# FROM pytorch/pytorch:2.0.1-cuda11.7-cudnn8-devel
FROM python:3.10
RUN mkdir -p /root/A2rchi
WORKDIR /root/A2rchi
COPY pyproject.toml pyproject.toml
COPY README.md README.md
COPY LICENSE LICENSE
COPY config config
COPY A2rchi A2rchi
RUN pip install --upgrade pip && pip install .

# manually install 0.4.12 of chroma without telemetry
COPY deploy/chroma/chroma deploy/chroma/chroma
RUN pip uninstall chromadb && cd deploy/chroma/chroma && pip install . && cd /root/A2rchi

CMD ["python", "-u", "A2rchi/bin/service_cleo.py"]
