apiVersion: v1
kind: Service
metadata:
  name: {{ name }}-grader
  labels:
    app: {{ name }}-grader
spec:
  selector:
    app: {{ name }}-grader
  ports:
    - name: grader-port
      port: {{ "{{ .Values.grader.port }}" }}  
      targetPort: {{ "{{ .Values.grader.externalPort }}" }}  
