apiVersion: v1
data:
  init.sql: |
    {{ init_sql | indent(4)}}
kind: ConfigMap
metadata:
  name:  {{ archi_name }}-postgres-init
  labels:
    app: {{ archi_name }}-postgres
  annotations:
    use-subpath: "true"