apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {{ name }}-postgres
  name:  {{ name }}-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    {{ "{{- toYaml .Values.postgres.pvc.resources | nindent 12 }}" }}
