apiVersion: v1
kind: Service
metadata:
  name: {{ name }}-postgres
  labels:
    app: {{ name }}-postgres
spec:
  type: {{ "{{ .Values.service_type }}" }}  
  selector:
    app: {{ name }}-postgres
  ports:
    - name: postgres
      protocol: TCP
      port: {{ "{{ .Values.postgres.port }}" }}  
      targetPort: {{ "{{ .Values.postgres.port }}" }}  