# syntax=docker/dockerfile:1
# FROM pytorch/pytorch:2.0.1-cuda11.7-cudnn8-devel
FROM python:3.10
RUN mkdir -p /root/A2rchi
WORKDIR /root/A2rchi
COPY pyproject.toml pyproject.toml
COPY README.md README.md
COPY LICENSE LICENSE
COPY config config
COPY a2rchi a2rchi
RUN pip install --upgrade pip && pip install .
