# syntax=docker/dockerfile:1
ARG TAG=from-env
FROM a2rchi-base:${TAG}
EXPOSE 7861

# ensure this directory is present for prod-801 deployment
RUN if [ "$BUILD_ENV" = "prod-801" ] ; then mkdir /root/data/801-content ; fi

CMD ["python", "-u", "A2rchi/bin/service_chat.py"]
