# syntax=docker/dockerfile:1
FROM python:3.10
RUN mkdir -p /root/A2rchi
WORKDIR /root/A2rchi
COPY pyproject.toml pyproject.toml
COPY README.md README.md
COPY LICENSE LICENSE
COPY config config
COPY A2rchi A2rchi
RUN pip install --upgrade pip && pip install .

CMD ["python", "-u", "A2rchi/bin/service_data_manager.py"]
