# syntax=docker/dockerfile:1
# FROM pytorch/pytorch:2.0.1-cuda11.7-cudnn8-devel
FROM python:3.10
RUN mkdir -p /root/A2rchi
WORKDIR /root/A2rchi
EXPOSE 7861
COPY pyproject.toml pyproject.toml
COPY README.md README.md
COPY LICENSE LICENSE
COPY config config
COPY A2rchi A2rchi
RUN pip install --upgrade pip && pip install .

CMD ["python", "-u", "A2rchi/bin/service_chat.py"]
