# syntax=docker/dockerfile:1

# create grafana directories
FROM grafana/grafana-enterprise:10.2.0
RUN mkdir -p /etc/grafana/provisioning/datasources
RUN mkdir -p /etc/grafana/provisioning/dashboards
RUN mkdir -p /var/lib/grafana/dashboards

# copy files into respective grafana directories
COPY deploy/grafana/datasources.yaml /etc/grafana/provisioning/datasources/
COPY deploy/grafana/dashboards.yaml /etc/grafana/provisioning/dashboards/
COPY deploy/grafana/a2rchi-default-dashboard.json /var/lib/grafana/dashboards/
