name: prod_801

global:
  TRAINED_ON: "8.01"

interfaces:
  chat_app:
    PORT: 7864
    EXTERNAL_PORT: 7864
    HOSTNAME: "t3desk018.mit.edu"

chains:
  input_lists:
    - env/801/miscellanea.list
    - env/801/801-textbook.list
  chain:
    MODEL_NAME: AnthropicLLM
    CONDENSE_MODEL_NAME: AnthropicLLM
    SUMMARY_MODEL_NAME: AnthropicLLM
  prompts:
    CONDENSING_PROMPT: env/801/condense.prompt
    MAIN_PROMPT: env/801/main.prompt
    SUMMARY_PROMPT: env/801/summary.prompt
