#!/usr/bin/env python3
"""Generate Ollama Modelfiles for the submit75 full-context matrix.

Produces six Modelfiles (3 base models × 2 thinking modes) under
`configs/submit75/modelfiles/`, each pinning the model's native
maximum context and (for thinking-off) the `SYSTEM /no_think`
directive.

Usage:

    python scripts/submit75/generate_modelfiles.py \
        --qwen-122b-num-ctx 65536  # optional fallback if 256K OOMs

The `--qwen-122b-num-ctx` override exists because qwen3.5:122b-a10b
may not fit its native context on 4× V100 32GB. Leave it unset to
use the model's full native context.

After generating, build each tag on submit75:

    for f in configs/submit75/modelfiles/*.Modelfile; do
        tag=$(basename "$f" .Modelfile)
        ollama create "$tag" -f "$f"
    done
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path


DEFAULT_OUTPUT_DIR = Path(__file__).resolve().parents[2] / "configs" / "submit75" / "modelfiles"


@dataclass(frozen=True)
class ModelSpec:
    base_tag: str          # what to FROM off in the Modelfile
    slug: str              # filename-safe name for the derived tags
    native_num_ctx: int    # native max context reported by the model
    renderer: str          # matches the `RENDERER` directive convention on submit75
    parser: str
    default_num_predict: int = 4096
    notes: str = ""


# These native context values come from the April 2026 Ollama library listings.
# Verify with `ollama show <base_tag>` on submit75 before building.
MODELS: list[ModelSpec] = [
    ModelSpec(
        base_tag="gemma4:26b",
        slug="gemma4-26b",
        native_num_ctx=262144,  # 256K per ollama.com listing
        renderer="gemma4",
        parser="gemma4",
        notes="MoE 26B-A4B, verify native ctx with `ollama show gemma4:26b`",
    ),
    ModelSpec(
        base_tag="qwen3.5:27b",
        slug="qwen3.5-27b",
        native_num_ctx=262144,  # 256K per ollama.com listing
        renderer="qwen3",
        parser="qwen3",
        notes="Dense 27B, verify native ctx with `ollama show qwen3.5:27b`",
    ),
    ModelSpec(
        base_tag="qwen3.5:122b-a10b",
        slug="qwen3.5-122b-a10b",
        native_num_ctx=262144,  # 256K nominal, likely reduced on V100 setup
        renderer="qwen3",
        parser="qwen3",
        notes="MoE 122B-A10B (~10B active). Likely needs num_ctx reduction for VRAM.",
    ),
]


MODELFILE_TEMPLATE = """\
# Generated by scripts/submit75/generate_modelfiles.py
# Base model: {base_tag}
# Thinking mode: {thinking_mode}
# num_ctx: {num_ctx}
#
# {notes}

FROM {base_tag}
TEMPLATE {{{{ .Prompt }}}}
{system_line}RENDERER {renderer}
PARSER {parser}
PARAMETER num_ctx {num_ctx}
PARAMETER num_predict {num_predict}
PARAMETER temperature 0.0
"""


def render_modelfile(spec: ModelSpec, *, thinking_on: bool, num_ctx: int) -> str:
    thinking_mode = "on" if thinking_on else "off"
    system_line = "" if thinking_on else "SYSTEM /no_think\n"
    return MODELFILE_TEMPLATE.format(
        base_tag=spec.base_tag,
        thinking_mode=thinking_mode,
        num_ctx=num_ctx,
        notes=spec.notes,
        system_line=system_line,
        renderer=spec.renderer,
        parser=spec.parser,
        num_predict=spec.default_num_predict,
    )


def derived_tag(spec: ModelSpec, *, thinking_on: bool) -> str:
    suffix = "think" if thinking_on else "nothink"
    return f"{spec.slug}-fullctx-{suffix}"


def write_modelfiles(
    output_dir: Path,
    *,
    overrides: dict[str, int] | None = None,
) -> list[Path]:
    overrides = overrides or {}
    output_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for spec in MODELS:
        num_ctx = overrides.get(spec.slug, spec.native_num_ctx)
        for thinking_on in (True, False):
            tag = derived_tag(spec, thinking_on=thinking_on)
            path = output_dir / f"{tag}.Modelfile"
            path.write_text(render_modelfile(spec, thinking_on=thinking_on, num_ctx=num_ctx))
            written.append(path)
    return written


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help=f"Where to write Modelfiles (default: {DEFAULT_OUTPUT_DIR})",
    )
    parser.add_argument(
        "--gemma4-26b-num-ctx",
        type=int,
        default=None,
        help="Override num_ctx for gemma4-26b variants",
    )
    parser.add_argument(
        "--qwen3.5-27b-num-ctx",
        type=int,
        default=None,
        help="Override num_ctx for qwen3.5-27b variants",
        dest="qwen_27b_num_ctx",
    )
    parser.add_argument(
        "--qwen3.5-122b-a10b-num-ctx",
        type=int,
        default=None,
        help="Override num_ctx for qwen3.5-122b-a10b variants (likely needed for VRAM)",
        dest="qwen_122b_num_ctx",
    )
    args = parser.parse_args()

    overrides: dict[str, int] = {}
    if args.gemma4_26b_num_ctx is not None:
        overrides["gemma4-26b"] = args.gemma4_26b_num_ctx
    if args.qwen_27b_num_ctx is not None:
        overrides["qwen3.5-27b"] = args.qwen_27b_num_ctx
    if args.qwen_122b_num_ctx is not None:
        overrides["qwen3.5-122b-a10b"] = args.qwen_122b_num_ctx

    written = write_modelfiles(args.output_dir, overrides=overrides)
    print(f"Wrote {len(written)} Modelfiles to {args.output_dir}:")
    for p in written:
        print(f"  {p.name}")
    print()
    print("Next steps on submit75:")
    print("  for f in configs/submit75/modelfiles/*.Modelfile; do")
    print('    tag=$(basename "$f" .Modelfile)')
    print('    ollama create "$tag" -f "$f"')
    print("  done")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
