# Configuration for dsrf-test with new template structure
name: dsrf-test-gpu

global:
  TRAINED_ON: "FASRC User Docs"

interfaces:
  uploader_app:
    verify_urls: false

# Data manager configuration (moved from utils)
data_manager:
  input_lists:
    - configs/dsrf_user_docs.list
  chunk_size: 15000
  embedding_name: HuggingFaceEmbeddings

# A2rchi pipeline configuration (new structure)
a2rchi:
  pipelines: [QAPipeline]  # Required: changed from 'pipeline' to 'pipelines' as list
  pipeline_map:
    QAPipeline:
      prompts:
        required:
          condense_prompt: configs/prompts/fasrc_condense.prompt
          chat_prompt: configs/prompts/fasrc_main.prompt
      models:
        required:
          condense_model: VLLM
          chat_model: VLLM

  # Model configurations
  model_class_map:
    VLLM:
      kwargs:
        base_model: 'Qwen/Qwen3-8B'
        quantization: false
        max_model_len: 32768
        tensor_parallel_size: 4
        repetition_penalty: 1.0
        gpu_memory_utilization: 0.8
      env:
        NCCL_P2P_DISABLE: "1"
        NCCL_IB_DISABLE: "1"
        NCCL_DEBUG: "INFO"
    HuggingFaceOpenLLM:
      kwargs:
        base_model: "Qwen/Qwen3-8B"
        quantization: true

locations_of_secrets:
  - ~/.a2rchi/base
