apiVersion: v1
data:
  {%- for input_list, content in input_lists.items() %}
  {{ input_list }}: |
    {{ content | indent(4) }}
  {%- endfor %}
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  name: {{ archi_name }}-data-manager-weblists
