apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ name }}-data-manager
  labels:
    app: {{ name }}-data-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ name }}-data-manager
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ name }}-data-manager
      annotations:
        rollout-timestamp: {{ "{{ now | quote }}" }}
    spec:
      automountServiceAccountToken: false
      containers:
        - name: {{ name }}-data-manager
          envFrom:
            - secretRef:
                name: {{ name }}-secrets
          env:
            - name: PGDATABASE
              value: archi-db
            - name: PGHOST
              value: {{ name }}-postgres
            - name: PGPORT
              value: "{{ "{{ .Values.postgres.port }}" }}"
            - name: PGUSER
              value: archi
            - name: VERBOSITY
              value: "{{ "{{ .Values.verbosity }}" }}"
          image: {{ "{{ .Values.data_manager.image }}" }}
          ports:
          - containerPort: {{ "{{ .Values.data_manager.port }}" }}
            protocol: TCP
          volumeMounts:
            - name: hf-cache
              mountPath: /.cache
            - mountPath: /root/.accounts
              name: root-accounts
            - mountPath: /root/data
              name: {{ name }}-data-manager-pvc
            - mountPath: /root/archi/configs
              name: {{ name }}-chat-config
            - mountPath: /root/archi/weblists
              name: {{ name }}-data-manager-weblists
              readOnly: True
{% if selenium_scraper %}
        - name: selenium-firefox
          image: selenium/standalone-firefox:latest
          ports:
            - containerPort: 4444
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
{% endif %}
      restartPolicy: Always
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 2Gi
        - name: hf-cache
          emptyDir: {}
        - emptyDir: {}
          name: root-accounts
        - name: {{ name }}-data-manager-pvc
          persistentVolumeClaim:
            claimName: {{ name }}-data-manager-pvc
        - configMap:
            name: {{ name }}-chat-config
          name: {{ name }}-chat-config
        - configMap:
            name: {{ name }}-data-manager-weblists
          name: {{ name }}-data-manager-weblists
