apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {{ name }}-data-manager-pvc
    service: {{ name }}-chat
    app: {{ name }}-chat
  name:  {{ name }}-data-manager-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    {{ "{{- toYaml .Values.data_manager.pvc.resources | nindent 12 }}" }}
