apiVersion: v1
kind: Service
metadata:
  name: {{ name }}-data-manager
  labels:
    app: {{ name }}-data-manager
spec:
  selector:
    app: {{ name }}-data-manager
  ports:
    - name: data-manager-port
      port: {{ "{{ .Values.data_manager.port }}" }}  
      targetPort: {{ "{{ .Values.data_manager.externalPort }}" }}  
