# syntax=docker/dockerfile:1
FROM docker.io/a2rchi/a2rchi-pytorch-base:latest 
RUN mkdir -p /root/A2rchi
WORKDIR /root/A2rchi

# maybe just throw everything into the same requirements file in the first place....
COPY LICENSE LICENSE


RUN apt-get update && apt-get install -y \
    nvidia-utils-550 \
    libnvidia-compute-550 \
    && rm -rf /var/lib/apt/lists/*

# Install Firefox and Geckodriver for Selenium 
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        wget \
        git \
        ca-certificates \
        libgtk-3-0 \
        libdbus-glib-1-2 \
        libasound2 \
        libx11-xcb1 \
        libxcomposite1 \
        libxdamage1 \
        libxrandr2 \
        libgbm1 \
        libnss3 \
        libxss1 \
        libxtst6 \
        libatk-bridge2.0-0 \
        libcups2 \
        libdrm2 \
        libxinerama1 \
        libglib2.0-0 \
        libpango-1.0-0 \
        libatk1.0-0 \
        libxext6 \
        libxfixes3 \
        libxrender1 \
        libxi6 \
        libfontconfig1 \
        libxrandr2 \
        libxcursor1 \
        libxinerama1 \
        libdbus-1-3 \
        libxt6 \
        libxcb-shm0 \
        libxcb1 \
        libxcb-dri3-0 \
        libxcomposite1 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
# Install Firefox ESR
RUN wget -O /tmp/firefox-esr.tar.bz2 "https://download.mozilla.org/?product=firefox-esr-latest-ssl&os=linux64&lang=en-US" && \
    tar -xjf /tmp/firefox-esr.tar.bz2 -C /opt/ && \
    ln -s /opt/firefox/firefox /usr/bin/firefox && \
    rm /tmp/firefox-esr.tar.bz2

# Install Geckodriver
RUN wget -q "https://github.com/mozilla/geckodriver/releases/download/v0.36.0/geckodriver-v0.36.0-linux64.tar.gz" \
    && tar -xzf "geckodriver-v0.36.0-linux64.tar.gz" -C /usr/local/bin \
    && chmod +x /usr/local/bin/geckodriver \
    && rm "geckodriver-v0.36.0-linux64.tar.gz"

COPY a2rchi_code src
COPY prompts prompts
COPY configs configs
COPY pyproject.toml pyproject.toml
#COPY weblists weblists
RUN pip install --upgrade pip && pip install .
CMD ["python", "-u", "src/bin/service_grader.py"]
# service_grader.py will just run the flask app as in service_chat.py ... don't even need the janky javascript templating function
