# syntax=docker/dockerfile:1
FROM docker.io/a2rchi/a2rchi-python-base:latest
RUN mkdir -p /root/archi
WORKDIR /root/archi

COPY LICENSE LICENSE

COPY archi_code src
COPY configs configs
COPY pyproject.toml pyproject.toml
COPY weblists weblists
RUN pip install --upgrade pip && pip install .

CMD ["python", "-u", "src/bin/service_jira.py"]
