# syntax=docker/dockerfile:1

# create grafana directories
FROM docker.io/grafana/grafana-enterprise:10.2.0
RUN mkdir -p /etc/grafana/provisioning/datasources
RUN mkdir -p /etc/grafana/provisioning/dashboards
RUN mkdir -p /var/lib/grafana/dashboards

# # copy files into respective grafana directories
#COPY grafana/datasources.yaml /etc/grafana/provisioning/datasources/
#COPY grafana/dashboards.yaml /etc/grafana/provisioning/dashboards/