# syntax=docker/dockerfile:1
FROM docker.io/a2rchi/a2rchi-python-base:latest 
RUN mkdir -p /root/A2rchi
WORKDIR /root/A2rchi

COPY LICENSE LICENSE

COPY a2rchi_code src
COPY prompts prompts
COPY configs configs
COPY pyproject.toml pyproject.toml
COPY weblists weblists
RUN pip install --upgrade pip && pip install .

CMD ["python", "-u", "src/bin/service_redmine.py"]
