# syntax=docker/dockerfile:1
FROM --platform=linux/amd64 docker.io/a2rchi/a2rchi-python-base:latest 
RUN mkdir -p /root/A2rchi
WORKDIR /root/A2rchi

COPY LICENSE LICENSE

#EXPOSE 7861

# ensure this directory is present for prod-801 deployment
# RUN if [ "$BUILD_ENV" = "prod-801" ] ; then mkdir /root/data/801-content ; fi

# Install Firefox and Geckodriver for Selenium 
RUN apt-get update && apt-get install -y \
    firefox-esr \
    wget \
    gnupg \
    git \
    ca-certificates \
    --no-install-recommends \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install Geckodriver
RUN wget -q "https://github.com/mozilla/geckodriver/releases/download/v0.36.0/geckodriver-v0.36.0-linux64.tar.gz" \
    && tar -xzf "geckodriver-v0.36.0-linux64.tar.gz" -C /usr/local/bin \
    && chmod +x /usr/local/bin/geckodriver \
    && rm "geckodriver-v0.36.0-linux64.tar.gz"

COPY a2rchi_code src
COPY prompts prompts
COPY configs configs
COPY pyproject.toml pyproject.toml
COPY weblists weblists
RUN pip install --upgrade pip && pip install .

RUN chmod g+rx /root; chmod -R g+w /root/A2rchi/src/interfaces

ARG APP_VERSION=unknown
ENV APP_VERSION=${APP_VERSION}

CMD ["python", "-u", "src/bin/service_chat.py"]
