# syntax=docker/dockerfile:1
FROM ghcr.io/chroma-core/chroma:1.2.1

# default arg (overwritten by compose if neeeded) then convert to env var
ARG CHROMA_PORT=8000
ENV CHROMA_PORT=${CHROMA_PORT}

RUN apt-get update -y && apt-get install -y curl

# permissions for OpenShift/OKD
# RUN chmod g+rx /root; chmod -R g+rwx /chroma

RUN echo "Chroma app running on $CHROMA_PORT, exposing"
EXPOSE $CHROMA_PORT

ENTRYPOINT []
# shell form to allow for env variable expansion
CMD ["sh", "-c", "chroma run --host 0.0.0.0 --port ${CHROMA_PORT:-8000}"]
