verbosity: {{ verbosity }}
archi:
  name: {{ archi_name }}

postgres:
  image: juanpablosalasg/archi-postgres:latest
  port: {{ postgres_port }}

chat:
  image: juanpablosalasg/archi-chat:latest
  port: {{ chatbot_port_host }}
  externalPort: {{ chatbot_port_container }}

data_manager:
  image: juanpablosalasg/archi-data-manager:latest
  port: {{ data_manager_port_host }}
  externalPort: {{ data_manager_port_container }}