verbosity: {{ verbosity }}
archi:
  name: {{ archi_name }}

service_type: ClusterIP
hostMode: {{ 'true' if host_mode else 'false' }}

postgres:
  image: juanpablosalasg/archi-postgres:latest
  port: {{ postgres_port }}
  resources:
    requests:
      cpu: "250m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  pvc:
    resources:
      requests:
        storage: "500Mi"
      limits:
        storage: "5Gi"

chat:
  image: juanpablosalasg/archi-chat:latest
  port: {{ chatbot_port_host }}
  externalPort: {{ chatbot_port_container }}
  resources:
    requests:
      cpu: "500m"
      memory: "500Mi"
    limits:
      cpu: "1000m"
      memory: "2Gi"
  pvc:
    resources:
      requests:
        storage: "100Mi"
      limits:
        storage: "250Mi"


data_manager:
  image: juanpablosalasg/archi-data-manager:latest
  port: {{ data_manager_port_host }}
  externalPort: {{ data_manager_port_container }}
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1000m"
      memory: "2Gi"
  pvc:
    resources:
      requests:
        storage: "100Mi"
      limits:
        storage: "250Mi"

{% if grafana.enabled %}
grafana:
  port: {{ grafana.port_host }}
  externalPort: {{ grafana.port_container }}
{% endif %}

{% if grader.enabled %}
grader:
  port: {{ grader.port_host }}
  externalPort: {{ grader.port_container }}
{% endif %}